/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import java.awt.Point;
import java.awt.event.KeyEvent;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import controller.GajiController;
/**
 *
 * @author gemma
 */
public class FormGaji extends javax.swing.JInternalFrame {

    private GajiController gajiController;
    private DefaultTableModel gajiDefaultTableModel;

    /**
     * Creates new form FormGaji
     */
    public FormGaji() {
        initComponents();
        
        gajiController = new GajiController();
        gajiDefaultTableModel = (DefaultTableModel) gajiTable.getModel();
        tutupButton.addActionListener(e -> dispose());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        pekerjaanPopupMenu = new javax.swing.JPopupMenu();
        tambahMenuItem = new javax.swing.JMenuItem();
        hapusMenuItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        simpanButton = new javax.swing.JButton();
        tutupButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ktpTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        gajiPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gajiTable = new javax.swing.JTable();
        ruangTextField = new javax.swing.JTextField();
        namaTextField = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        tambahMenuItem.setText("jMenuItem1");
        tambahMenuItem.addActionListener(this::tambahMenuItemActionPerformed);
        pekerjaanPopupMenu.add(tambahMenuItem);

        hapusMenuItem.setText("jMenuItem2");
        hapusMenuItem.addActionListener(this::hapusMenuItemActionPerformed);
        pekerjaanPopupMenu.add(hapusMenuItem);

        setTitle("Mengelola Gaji Karyawan");

        simpanButton.setText("Simpan");
        simpanButton.addActionListener(this::simpanButtonActionPerformed);

        tutupButton.setText("Tutup");

        jLabel1.setText("KTP");

        jLabel2.setText("Nama");

        ktpTextField.addActionListener(this::ktpTextFieldActionPerformed);
        ktpTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ktpTextFieldKeyPressed(evt);
            }
        });

        jLabel3.setText("Ruang");

        gajiPanel.setToolTipText("gajiTable");

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseReleased(evt);
            }
        });

        gajiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Nama Pekerjaan", "Gaji Bersih", "Gaji Kotor", "Tunjangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        gajiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                gajiTableMouseReleased(evt);
            }
        });
        gajiTable.addPropertyChangeListener(this::gajiTablePropertyChange);
        gajiTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gajiTableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(gajiTable);

        javax.swing.GroupLayout gajiPanelLayout = new javax.swing.GroupLayout(gajiPanel);
        gajiPanel.setLayout(gajiPanelLayout);
        gajiPanelLayout.setHorizontalGroup(
            gajiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
            .addGroup(gajiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gajiPanelLayout.createSequentialGroup()
                    .addGap(79, 79, 79)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(80, Short.MAX_VALUE)))
        );
        gajiPanelLayout.setVerticalGroup(
            gajiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
            .addGroup(gajiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gajiPanelLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(59, 59, 59)
                        .addComponent(ktpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ruangTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(namaTextField)))
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simpanButton)
                    .addComponent(tutupButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(gajiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 243, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ktpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ruangTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(simpanButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tutupButton))
                .addGap(18, 18, 18)
                .addComponent(gajiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(685, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
public void setKtp(String ktp) {
    ktpTextField.setText(ktp);
}

public void setNama(String nama) {
    namaTextField.setText(nama);
}

public void setRuang(String ruang) {
    ruangTextField.setText(ruang);
}

public void setNamaPekerjaan(String nama) {
    gajiTable.setValueAt(
        nama,
        gajiTable.getSelectedRow(),
        1
    );
}

/**
 * Menambahkan satu baris data gaji ke tabel.
 * Dipanggil oleh GajiController saat memuat data dari database.
 *
 * @param rowData array data baris: {kode, namaPekerjaan, gajiBersih, gajiKotor, tunjangan}
 */
public void setTambahGaji(Object[] rowData) {
    gajiDefaultTableModel.addRow(rowData);
}

public void hapusGaji() {
    for (int i = 2; i <= 4; i++) {
        gajiTable.setValueAt(
            "",
            gajiTable.getSelectedRow(),
            i
        );
    }
}

public void clearGajiTable() {
    gajiDefaultTableModel.setRowCount(0);
}

private void klikKananTabel(java.awt.event.MouseEvent evt) {
    if (evt.isPopupTrigger()) {
        pekerjaanPopupMenu.show(
            evt.getComponent(),
            evt.getX(),
            evt.getY()
        );
    }
}
    private void ktpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ktpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ktpTextFieldActionPerformed

    private void tambahMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahMenuItemActionPerformed
        // TODO add your handling code here:
        gajiController.tampilkanFormLihatPekerjaan();
    }//GEN-LAST:event_tambahMenuItemActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        // TODO add your handling code here:
        gajiController.simpan (ktpTextField, gajiTable);
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void jScrollPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseReleased
        // TODO add your handling code here:
        klikKananTabel(evt);
    }//GEN-LAST:event_jScrollPane1MouseReleased

    private void gajiTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gajiTableKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (gajiTable.getSelectedRow() == (gajiTable.getRowCount()-1)) {
                if (gajiTable.getSelectedColumn()==0) {
                    gajiDefaultTableModel.insertRow(gajiDefaultTableModel.getRowCount(), new Object[]{});
                } else {
                    if (gajiTable.getSelectedColumn() == (gajiTable.getColumnCount()-1)) {
                    gajiDefaultTableModel.insertRow(gajiDefaultTableModel.getRowCount(), new Object[]{});
                    gajiTable.changeSelection (gajiTable.getSelectedRow(), 0, false, false);
                } else {
                    gajiTable.changeSelection(gajiTable.getSelectedRow(), gajiTable.getSelectedColumn()+1, false, false);
                }
                }
                } else {
                if (gajiTable.getSelectedColumn() == (gajiTable.getColumnCount()-1)) {
                    gajiTable.changeSelection (gajiTable.getSelectedRow()+1, 0, false, false);
                } else {
                    gajiTable.setColumnSelectionInterval (gajiTable.getSelectedColumn()+1,gajiTable.getSelectedColumn()+1);
                    gajiTable.setRowSelectionInterval (gajiTable.getSelectedRow()+1,gajiTable.getSelectedRow()+1);
                }
            }
        }
    }//GEN-LAST:event_gajiTableKeyPressed

    private void gajiTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gajiTableMouseReleased
        // TODO add your handling code here:
    Point p = evt.getPoint();
    int rowNumber = gajiTable.rowAtPoint (p);
    ListSelectionModel model = gajiTable.getSelectionModel();
    model.setSelectionInterval (rowNumber, rowNumber);
    
    klikKananTabel (evt);
    }//GEN-LAST:event_gajiTableMouseReleased

    private void gajiTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_gajiTablePropertyChange
        // TODO add your handling code here:
        if (gajiTable.getSelectedRowCount()>0) {
            if (gajiTable.getSelectedColumn()==0) {
                String kodePekerjaan = "";
                try{
                    kodePekerjaan = gajiTable.getValueAt(gajiTable.getSelectedRow(), 0).toString();
                }catch (Exception ex) {}

                if (!kodePekerjaan.equals("")) {
                    gajiController.cariPekerjaan (kodePekerjaan);
                }
            }
        }
    }//GEN-LAST:event_gajiTablePropertyChange

    private void ktpTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ktpTextFieldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            gajiController.cariKaryawan(ktpTextField);
        }   
    }//GEN-LAST:event_ktpTextFieldKeyPressed

    private void hapusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusMenuItemActionPerformed
        // TODO add your handling code here:
        if (gajiTable.getSelectedRowCount() > 0) {
            gajiDefaultTableModel.removeRow(
                gajiTable.getSelectedRow());
        }
    }//GEN-LAST:event_hapusMenuItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gajiPanel;
    private javax.swing.JTable gajiTable;
    private javax.swing.JMenuItem hapusMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ktpTextField;
    private javax.swing.JTextField namaTextField;
    private javax.swing.JPopupMenu pekerjaanPopupMenu;
    private javax.swing.JTextField ruangTextField;
    private javax.swing.JButton simpanButton;
    private javax.swing.JMenuItem tambahMenuItem;
    private javax.swing.JButton tutupButton;
    // End of variables declaration//GEN-END:variables
}
