name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Build JAR
        shell: cmd
        run: ant clean jar

      - name: Create Windows Installer
        shell: cmd
        run: >
          jpackage
          --type exe
          --name AplikasiGajiKaryawanPTSintory
          --input dist
          --main-jar AplikasiGaji.jar
          --main-class aplikasgajikaryawanptsintory.AplikasGajiKaryawanPTSintory
          --dest output
          --win-shortcut
          --win-menu
          --win-menu-group "Aplikasi Gaji"

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: AplikasiGaji-Windows
          path: output/*.exe
